language: go
go:
  - 1.x

before_install:
  # use local source tree when testing forks
  - mkdir -p $GOPATH/src/github.com/dop251/goja
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/dop251/goja/ || true

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet .
  - go test -v -short -race ./...
