language: go
go:
  - 1.x

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 RACE="-race"
  - GIMME_OS=linux GIMME_ARCH=386

before_install:
  # use local source tree when testing forks
  - mkdir -p $GOPATH/src/github.com/dop251/
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/dop251/ || true

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet .
  - go test -short $RACE ./...
