language: go
go:
  - 1.x

before_install:
  # use local source tree when testing forks
  - ls -l $TRAVIS_BUILD_DIR
  - mkdir -p $GOPATH/src/github.com/dop251/
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/dop251/ || true

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet .
  - go test -short -race ./...
