language: go
go:
  - 1.x

go_import_path: github.com/dop251/goja

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 RACE="-race"
  - GIMME_OS=linux GIMME_ARCH=386

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet .
  - go test -short $RACE ./...
