on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.x]
        os: [ubuntu-latest]
        arch: ["", "386"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check formatting
        run: diff -u <(echo -n) <(gofmt -d .)
      - name: Checkout tc39 tests
        run: ./.tc39_test262_checkout.sh
      - name: Run tests
        env:
          GOARCH: ${{ matrix.arch }}
        run: go test ./...
